# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'GoReleaser Action'
description: 'GitHub Action for GoReleaser, a release automation tool for Go projects'
author: 'crazy-max'
branding:
  color: 'green'
  icon: 'package'

inputs:
  version:
    description: 'GoReleaser version. Example: v0.118.0'
    default: 'latest'
  args:
    description: 'Arguments to pass to GoReleaser'
  key:
    description: 'Deprecated. Use goreleaser/goreleaser-action@v2 alongside crazy-max/ghaction-import-gpg'
    deprecationMessage: 'The key input will not be supported. Use goreleaser/goreleaser-action@v2 alongside crazy-max/ghaction-import-gpg'
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'

runs:
  using: 'node12'
  main: 'dist/index.js'
