name: test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        version:
          - latest
          - v0.117.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@master
      -
        name: GoReleaser
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: release --snapshot --rm-dist
